# Generated by Django 2.0.6 on 2019-10-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='address',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='description',
            new_name='code',
        ),
    ]
